name: ruff - linter & formatter
on:
  push:
    branches:
      - '*'
    paths:
      - .github/workflows/ruff.yaml
      - src/**
      - test/**
      - ruff.toml

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install ruff

      - name: Run ruff linter
        run: ruff check --no-cache

      - name: Run ruff formatter
        run: ruff format --check --no-cache
